### ISSUE TITLE
Performance measurements or config recommendations available?

### ISSUE THREAD

**Issue by nitram509** [google/ngx_brotli#10]
Hi,

I'm working on wrapping Brotli into a Java library to make it available to Java developers.
My goal is similar to what ngx_brotli does: I want to enable such compression in Java based HTTP servers.

I'm curios if someone of you did performance measurements?
Or maybe can recommend certain config settings (e.g. buffer and window size) for ngx_brotli.

Background information:
My current benchmarks on canterburry corpus (cp.hml) shows
that gzip (default level) is roughly twice as fast as brotli (level 5).
(See https://github.com/nitram509/jbrotli).

**Comment by PiotrSikora** [comment]
Hey Mark,
interesting, on my machine (Xeon E5-1650v3), they take about the same CPU time.

Also, I think that you're comparing wrong things, because Brotli at quality 5 results in much better compression than gzip at level 6 (default):

For Canterbury Corpus:
- Brotli at quality 1 results in better compression (661,992 bytes, **~9% smaller**) than gzip at level 9 (730,732 bytes), while taking **10x less CPU time**.
- Brotli at quality 5 results in much better compression (565,539 bytes, **~23% smaller**) than gzip at level 6 (733,769 bytes), while taking pretty much **the same CPU time**.

For [List of Advanced Dungeons & Dragons 2nd edition monsters](https://en.wikipedia.org/wiki/List_of_Advanced_Dungeons_%26_Dragons_2nd_edition_monsters):
- Brotli at quality 1 results in **the same compression** (87,478 bytes) as gzip at level 9 (87,474 bytes), while taking **6x less CPU time**.
- Brotli at quality 5 results in much better compression (74,877 bytes, **~16% smaller**) than gzip at level 6 (89,047 bytes), while taking pretty much **the same CPU time**.

Anyway, please email me at piotrsikora@google.com and I'll connect you with the correct people.
