### ISSUE TITLE
question about test case

### ISSUE THREAD

**Issue by chobits** [google/ngx_brotli#45]
hi Piotr,
  I found there is no test case included into this repo. Is there any test cases (e.g. `t/brotli.t`) within google?

**Comment by eustas** [comment]
We would appreciate, if someone donates the test cases.
Due to exposed test API, testing brotli compression seems to be quite untrivial.
Instead we run tests on Travis CI - just build and run nginx, make requests and compare the output.

Feel free to re-open this bug, if that kind of testing seems to be "not enough".
