### ISSUE TITLE
Document whether `ngx_http_brotli_filter_module` caches or not

### ISSUE THREAD

**Issue by mikemaccana** [google/ngx_brotli#48]
A lot of the decision between using `ngx_http_brotli_filter_module` or `ngx_http_brotli_static_module` depends on whether the former has an in-memory-cache or not. If `ngx_http_brotli_filter_module` is throwing away previous results then there's a latency hit for every time a resource is requested, if not then it's only for the first time a given resource is requested. 

I can't see a cache in `ngx_http_brotli_filter_module` (not a C developer) and I can't see any ngionx directives to control cache size, so I suspect the answer is 'there is no cache right now' but it would be nice to have confirmation either way.

Thanks!

**Comment by eustas** [comment]
Brotli  is not much different from gzip.

https://serverfault.com/questions/910069/does-nginx-compress-files-for-every-request-with-gzip-on

From nginx point of view, content is produced by a chain of filters.
Bottom-most filter might read something from filesystem.
Typically this layer cares about caching.

Middle filters do transform content - e.g. process PHP, or compress.

Top filters talk to clients.

Everything is streamed, so top levels can not say, if the resulting response is going to be the same as before -> can not decide, if something should be taken from cache.

Given that:
 * if content is static - it should be precompressed with maximal quality
 * otherwise - only the "raw" data read from disk is cached - compression is repeated for every request
