### ISSUE TITLE
Add option to compress proxied requests

### ISSUE THREAD

**Issue by oscarvalente** [google/ngx_brotli#53]
Gzip nginx module supports [`gzip_proxied`](http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_proxied) option that
> Enables or disables gzipping of responses for proxied requests

Likewise it was useful to have a brotli one (`brotli_proxied`) :)

**Comment by PiotrSikora** [comment]
`ngx_brotli` compresses proxied requests just fine, without any additional configuration (effectively using `brotli_proxied any` instead of `brotli_proxied off` as the default).

Do you have a use case where this would be undesirable behavior that cannot be controled by `brotli on|off`?

**Comment by oscarvalente** [comment]
Thanks for the clarification!
>  a use case where this would be undesirable behavior

At the moment I don't, but it's quite an interesting scenario 😄. Closing this issue...

**Comment by iamriajul** [comment]
I need `brotli_proxied off`, My idea is only to compress the response using brotli if the request doesn't have the `Via` header, meaning the request isn't coming through a CDN like CloudFront.

I'm using CloudFront and CloudFront support compressing the response using its own infrastructure that's why I don't  want to compress the response using my EC2 instances so they are more available to do other works!.

And if sometimes the CDN goes down, then I can just swap the DNS records to EC2 instances, then I don't have to configure compression separately, It just works.

I hope you get my point.
