### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by whitekyo** [google/ngx_brotli#87]
<img width="1222" alt="屏幕快照 2019-10-11 上午11 06 23" src="https://user-images.githubusercontent.com/5258260/66621648-874ec480-ec17-11e9-82ff-6e1a0455af75.png">
<img width="1238" alt="屏幕快照 2019-10-11 上午11 06 49" src="https://user-images.githubusercontent.com/5258260/66621657-8cac0f00-ec17-11e9-93a7-4556d7e7c1c3.png">

**Comment by whitekyo** [comment]
the same js file, When I use h2 brotli。 the size of js file can't change to smaller, what is wrong?

It's my nginx conf
<img width="191" alt="屏幕快照 2019-10-11 上午11 11 57" src="https://user-images.githubusercontent.com/5258260/66621809-03e1a300-ec18-11e9-99b2-8045391bbae9.png">

**Comment by eustas** [comment]
Compressed h2 headers? Devtools show traffic for the "stream". Streams are multiplexed in h2 and share some info (e.g. headers).

Also h2, unlike http1.1 "compress" headers (not really, because of "CRIME", but somewhat)...

**Comment by Jas0n99** [comment]
Brotli will work for 1.1 or 2, however it only is enabled with HTTPS, otherwise you will probably notice it's compressed with gzip (if also enabled).

Yes, I know HTTP/2 should only be enabled with HTTPS, but there *are* ways around that if you configure nginx a certain way, and without giving us more info it's kind of hard to know what all is going on.
